choco install googlechrome -y
choco install firefox -y
choco install notepadplusplus -y
choco install 7zip -y
choco install python -y
choco install vlc -y
choco install vscode -y
choco install winscp  -y
choco install vim -y
choco install everything -y
choco install windirstat -y
choco install github-desktop -y
choco install pycharm-community -y
choco install microsoft-windows-terminal -y